# server port
server:
  port: 1010

mongodb:
  primary:
    uri: mongodb://test:123456@119.29.179.253:27017/test
    database: test

  secondary:
    database: test
    uri: mongodb://test:123456@119.29.179.253:27018/test