server:
  port: 1020

spring:
    datasource:
      url: jdbc:mysql://119.29.179.253:3306/shiro?useUnicode=true&characterEncoding=utf-8
      username: geelop
      password: geelop
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update

      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
       cache: false
       mode: LEGACYHTML5

# Shiro

shiro:
  web:
    enabled: true
  loginUrl: /login.html
  unauthorizedUrl: /a/unauthorized
  successUrl: /index
  userNativeSessionManager: true
  sessionManager:
    sessionIdUrlRewritingEnabled: false



